env:
  global:
  - AMAZON_S3_BUCKET=musicglue-bundle-cache
  - AMAZON_ACCESS_KEY_ID=AKIAITNVCO5SLJMTVVYQ
  - secure: "REHJcCN3LTqRs88k1jzTZhg5n+1GcpGnw3GAI21pSejTC/rjGQqSA1g4knrsW5zQ1Qk8tMaae4vxlNxzI7X0PW92pNS5SjmIkCrejhTLdMvY1w0vCR92T8k488Mw/ONLqi4LlWEpueDHj8ic7rPxTY2Agl75eoIST9QcQ6M9CdI="

rvm:
  - ruby-2.2.0

language: ruby

bundler_args: "--without development"

install:
  - "./script/cached-bundle install --deployment"

script:
  - bundle exec rake test:all

notifications:
  hipchat: 4c9312238a5ef355ef8e321fc2bab7@Music Glue

sudo: false
